services:
  backend:
    build: ./backend
    ports:
      - 8081:8081
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - 3000:80 # 80 inside container (nginx) → 3000 on host
    depends_on:
      - backend

  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # use same as in .env
      MYSQL_DATABASE: crud_app
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s # give MySQL up to 30s to initialize

volumes:
  db_data:
